# Your Name or Company
title: Nu'man Nashif Annawwaf

# Description of your website. This is used for social sharing.
description:  Designs, talks, and Developers Android with Java, Kotlin, and Flutter. I share Develops tutorials, free resources and inspiration. Loves music & gaming.

# A brief blurb about yourself
content: Designs, talks, and Developers Android with Java, Kotlin, and Flutter. I share Develops tutorials, free resources and inspiration. Loves music & gaming.

# Add your social links
social:
  - platform: github
    url: https://github.com/elhazent
  - platform: facebook
    url: https://www.facebook.com/numanannawwaf
  - platform: twitter
    url: https://twitter.com/elhazent
  - platform: linkedin
    url: elhazent

# General settings
url: http://sudo-elhazent.github.com/elhazent
baseurl: "/elhazent" 
markdown: kramdown
sharing_image: share.jpg
google_analytics: "UA-58263416-1" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center

theme: jekyll-theme-cayman
