# Site
name: Nu'man Nashif Annawwaf
description: Just another website
meta_description: Just another website
logo: /assets/images/logo.png
favicon: /assets/images/favicon.ico
paginate: 6
baseurl:
email: 'elhazent.mail@gmail.com'
google_analytics:
disqus:
sharethis:

# Authors
authors:
  john:
    name: Nu'man
    display_name: Nu'man Nashif Annawwaf
    image: /assets/images/john.jpg
    email: hello@john.doe
    web: example.com
    twitter:
    description: Hi, I am Nu'man Nashif Annawwaf.

# Plugins
plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-seo-tag

permalinks: pretty

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: 'category/:name/'

# Other
markdown: kramdown
highlighter: rouge

# SEO
twitter:
  username: john
  card: summary

facebook:
  app_id:
  publisher: john.com
  admins:

social:
name: Nu'man Nashif Annawwaf
links:
    - https://twitter.com/elhazent
    - https://www.facebook.com/numanannawwaf
    - https://www.linkedin.com/in/elhazent
    - https://github.com/elhazent
